[package]
name = "stream_throttle"
version = "0.2.1"
description = "Provides a Stream combinator, to limit the rate at which items are produced."
readme = "README.md"
license = "MIT"
authors = ["Mike Caines"]
repository = "https://github.com/mikecaines/stream-throttle"
categories = ["asynchronous"]
keywords = ["async", "futures", "stream", "throttle"]
documentation = "https://docs.rs/stream_throttle/"
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
log = "0.4"
futures = "0.3.1"
tokio = { version = "0.2", features = ["time"] }
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
